### ISSUE TITLE
Please publish the jar in maven central

### ISSUE THREAD

**Issue by soid** [chbatey/kafka-unit#2]
I couldn't find the artifact. It's quite handy to be able to just define the dependency and start using it.

**Comment by chbatey** [comment]
Hi @soid it is there: http://search.maven.org/#artifactdetails%7Cinfo.batey.kafka%7Ckafka-unit%7C0.1.2%7Cjar

**Comment by chbatey** [comment]
I added the mvn dependency details to README to make it easier to find

**Comment by soid** [comment]
Thank you!
