### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by velocipedist** [chbatey/kafka-unit#5]
Would it be possible to add a license to this project. Apache 2.0 would be ideal. We would like to use it, but cannot proceed without clear licensing terms. Cheers.

**Comment by chbatey** [comment]
Yeah np, I'll get to it this week

**Comment by velocipedist** [comment]
cheers!

**Comment by chbatey** [comment]
I've added Apache 2.0 to all the files + checked in LICENSE at the root level and pushed 2.0 to mvn central.

**Comment by velocipedist** [comment]
thanks!
