### ISSUE TITLE
1.0 is not available in Maven

### ISSUE THREAD

**Issue by buremba** [chbatey/kafka-unit#62]
The README file mentions version `1.0` but it's not available in central Maven repository.

**Comment by Qnzvna** [comment]
bump

**Comment by rmannibucau** [comment]
up

**Comment by cwensel** [comment]
is there another repo this is being published to?
http://repo1.maven.org/maven2/info/batey/kafka/kafka-unit/

**Comment by cwensel** [comment]
Also, for those interested, i've published my 0.11 fixes to
http://conjars.org/thirdparty/kafka-unit

**Comment by tscrowley** [comment]
bump

**Comment by StephenFox1995** [comment]
BUMP

**Comment by jpscaduto** [comment]
bump

**Comment by chbatey** [comment]
Sorry for the delay, syncing to maven central now

**Comment by nattyddubbs** [comment]
Still not seeing in [maven](https://mvnrepository.com/artifact/info.batey.kafka/kafka-unit).

**Comment by chbatey** [comment]
Sorry i missed the last button click to release it in maven central, on its way there now!
